FILESEXTRAPATHS_prepend := "${THISDIR}/files:"
SRC_URI += " file://socat-1.8.0.0.patch"
DEPENDS_remove = "openssl"
EXTRA_AUTORECONF_remove = "--exclude=autoheader"
DEPENDS += "wolfssl"
EXTRA_OECONF += "--with-wolfssl=${STAGING_EXECPREFIXDIR}"
