#Adjust these as needed
WOLFPROVIDER_VERSION ?= ""

WOLFPROVIDER_LICENSE ?= "WolfSSL_LicenseAgmt_JAN-2022.pdf"
WOLFPROVIDER_LICENSE_MD5 ?= "be28609dc681e98236c52428fadf04dd"

WOLFPROVIDER_SRC ?= ""
WOLFPROVIDER_SRC_SHA ?= ""
WOLFPROVIDER_SRC_PASS ?= ""

#Do not adjust these variables
PR = "commercial"
PV = "${WOLFPROVIDER_VERSION}"

BBFILE_PRIORITY='1'