#Adjust these as needed
WOLFPROVIDER_VERSION ?= ""

WOLFPROVIDER_LICENSE ?= "WolfSSL_LicenseAgmt_JAN-2024.pdf"
WOLFPROVIDER_LICENSE_MD5 ?= "9b56a02d020e92a4bd49d0914e7d7db8"

WOLFPROVIDER_SRC ?= ""
WOLFPROVIDER_SRC_SHA ?= ""
WOLFPROVIDER_SRC_PASS ?= ""

#Do not adjust these variables
PR = "commercial"
PV = "${WOLFPROVIDER_VERSION}"

BBFILE_PRIORITY='1'