FILESEXTRAPATHS_prepend := "${THISDIR}/files:"
SRC_URI += "file://openssh-8.5p1.patch"
DEPENDS_remove = "openssl"
DEPENDS += "virtual/wolfssl"
EXTRA_OECONF += "--with-wolfssl=${STAGING_EXECPREFIXDIR}"
