#Adjust these as needed
WOLFENGINE_VERSION ?= ""

WOLFENGINE_LICENSE ?= "WolfSSL_LicenseAgmt_JAN-2024.pdf"
WOLFENGINE_LICENSE_MD5 ?= "9b56a02d020e92a4bd49d0914e7d7db8"
WOLFENGINE_SRC ?= ""
WOLFENGINE_SRC_SHA ?= ""
WOLFENGINE_SRC_PASS ?= ""

#Do not adjust these variables
PR = "commercial"
PV = "${WOLFENGINE_VERSION}"

BBFILE_PRIORITY='1'